### PR TITLE
Add support for different circles for each door

### PR DESCRIPTION
**Pull request by omega**
This allows us to have a set of circles for each door, and without
membership in that circle, you wont be able to open that door.

This check does not apply to employees of companies, only for paying
members.

If you attempt to open multiple doors, none will open if you lack any of
the circles.

For now all doors have `door` only, this is intended used at BV9 to
limit access to certain areas.

https://github.com/bitraf/infrastructure/issues/149

### CODE REVIEW

**Comment by omega** [comment]
this is very "least possible effort", so no UI changes for now, just the backend support

**Comment by omega** [comment]
one thing I am unsure about, is if the buttons on the frontpage should only show up if you have the `door` circle (today that is the case, with this PR, it would show up for any paying member, but the buttons would give error with missing cirlces)

**Review by trygvis — APPROVED** [review]
This is a good start, showing inaccessible doors is fine.

I think we want the list of doors to be served by the backend soon, that way we can have some more control over what we expose.

**Comment by omega** [comment]
Yeah we want that at some point 🙂

**Pull request merged**
